### ISSUE TITLE
./pyKAN show_settings returns error

### ISSUE THREAD

**Issue by SYZYGY-DEV333** [ajventer/pyKAN#11] opened 2016-10-10 14:30 UTC
`./pyKAN show_settings` returns the following error:

```
Traceback (most recent call last):
  File "./pyKAN", line 332, in <module>
    settings = pykancfg.PyKANSettings(kspdir)
  File "~/.local/share/Steam/SteamApps/common/Kerbal Space Program/pyKAN-0.0.1/libPyKAN/pykancfg.py", line 44, in __init__
    self.save()
  File "~/.local/share/Steam/SteamApps/common/Kerbal Space Program/pyKAN-0.0.1/libPyKAN/pykancfg.py", line 69, in save
    util.mkdir_p(os.path.dirname(self.KSPSettingsFile))
AttributeError: 'PyKANSettings' object has no attribute 'KSPSettingsFile'
```

Is this because I have not assigned a kspdir?

**Comment by ajventer** [comment] 2016-10-10 14:31
Yes, thought there is defensive code that's supposed to prevent that. Guess there's a bug in that. I'll have a look tonight.

**Comment by ajventer** [comment] 2016-10-10 16:33
Just pushed a fix for this bug, and a bunch of other bugs caused by the python3 conversion. You should be good to go. I want to do some more testing - especially on the known bad modules - but this will probably become beta2 with a  few more changes.

**Closed as completed** 2016-10-10 17:29 UTC
